[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "foreman"
version = "0.1.0"
description = "LangGraph Foreman Agent project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langgraph",
    "langgraph-cli[inmem]",
    "python-dotenv",
    "langchain-openai",
]

[tool.setuptools.packages.find]
where = ["src"]
